/**
 * Lead Generation Planning Module (SUP-001)
 * 
 * Pure planning function that generates execution plans for lead generation
 * without actually executing tools or making external calls.
 */

// ========================================
// TOOL IDENTIFIERS
// ========================================

export type LeadToolIdentifier =
  | "GOOGLE_PLACES_SEARCH"
  | "HUNTER_DOMAIN_LOOKUP"
  | "HUNTER_ENRICH"
  | "EMAIL_SEQUENCE_SETUP"
  | "LEAD_LIST_SAVE"
  | "MONITOR_SETUP";

// ========================================
// TOOL PARAMETERS
// ========================================

export type LeadToolParams = Record<string, unknown>;

export interface GooglePlacesSearchParams {
  query: string;
  region: string;
  country?: string;
  maxResults?: number;
}

export interface HunterDomainLookupParams {
  companyName?: string;
  website?: string;
  country?: string;
  sourceStepId?: string;
}

export interface HunterEnrichParams {
  domain?: string;
  roleHint?: string;
  maxContactsPerDomain?: number;
  sourceStepId?: string;
}

export interface EmailSequenceSetupParams {
  campaignName: string;
  fromIdentityId: string;
  targetSegmentId?: string;
  estimatedVolume?: number;
  startTiming?: string;
  sourceListStepId?: string;
}

export interface LeadListSaveParams {
  sourceStepId: string;
  listName: string;
  region?: string;
  persona?: string;
  estimatedVolume?: number;
}

export interface MonitorSetupParams {
  sourceListStepId: string;
  cadence: "daily" | "weekly" | "monthly";
  signalTypes?: string[];
}

// ========================================
// PLAN STEP
// ========================================

export interface LeadGenPlanStep {
  /**
   * Unique ID within the plan, e.g. "step_1", "google_places_1".
   */
  id: string;

  /**
   * High-level label for humans, optional but useful.
   */
  label?: string;

  /**
   * Which tool this step intends to call.
   */
  tool: LeadToolIdentifier;

  /**
   * Parameters to feed into that tool when the executor runs it.
   */
  params: LeadToolParams;

  /**
   * IDs of other steps that must be completed before this one can run.
   */
  dependsOn?: string[];

  /**
   * Optional notes / rationale for the planner / debugger.
   */
  note?: string;
}

// ========================================
// GOAL AND CONTEXT
// ========================================

export interface LeadGenGoal {
  /**
   * Free-text from the user, as captured by the UI.
   */
  rawGoal: string;

  /**
   * Region(s) to target, e.g. "North West", "UK", "London and South East".
   */
  targetRegion?: string;

  /**
   * Persona or role, e.g. "pub landlords", "bar managers", "buyers".
   */
  targetPersona?: string;

  /**
   * Approximate number of leads or emails.
   */
  volume?: number;

  /**
   * Timing requirement, e.g. "this week", "ongoing weekly", ISO datetime, etc.
   */
  timing?: string;

  /**
   * Channels the user cares about. For now mostly email.
   */
  preferredChannels?: Array<"email" | "phone" | "linkedin">;

  /**
   * Whether the user wants ongoing monitoring as part of this goal.
   */
  includeMonitoring?: boolean;
}

/**
 * Environment & user-specific context the planner can use.
 */
export interface LeadGenContext {
  userId: string;
  accountId?: string;

  /**
   * Default country/region if goal doesn't specify.
   */
  defaultRegion?: string;
  defaultCountry?: string;

  /**
   * Default sending identity / email profile ID for outreach tools.
   */
  defaultFromIdentityId?: string;

  /**
   * Any saved preferences or flags (can be expanded later).
   */
  preferences?: Record<string, unknown>;
}

// ========================================
// PLAN OBJECT
// ========================================

export interface LeadGenPlan {
  /**
   * Unique identifier for this plan. Can be generated by Supervisor.
   */
  id: string;

  /**
   * A short description / title, often derived from the goal.
   */
  title: string;

  /**
   * Original raw goal text (or summary) from UI / goal capture.
   */
  rawGoal: string;

  /**
   * Optional structured goal fields.
   */
  goal: LeadGenGoal;

  /**
   * Context used to generate the plan (user, account, etc.).
   */
  context: LeadGenContext;

  /**
   * Ordered list of steps.
   */
  steps: LeadGenPlanStep[];

  /**
   * Optional metadata (e.g. createdAt, priority).
   */
  createdAt: string; // ISO timestamp
  priority?: "low" | "normal" | "high";
}

// ========================================
// PURE PLANNING FUNCTION
// ========================================

/**
 * Pure planning function that generates a lead generation execution plan.
 * 
 * IMPORTANT: This function does NOT execute tools or make external calls.
 * It only constructs a plan (DAG of steps) that can be executed later.
 * 
 * @param goal - The lead generation goal (what the user wants)
 * @param context - User and environment context
 * @returns A complete LeadGenPlan with ordered steps
 */
export function planLeadGeneration(
  goal: LeadGenGoal,
  context: LeadGenContext
): LeadGenPlan {
  // Step counter for generating unique IDs
  let stepCounter = 0;
  const steps: LeadGenPlanStep[] = [];

  function nextStepId(prefix: string): string {
    stepCounter += 1;
    return `${prefix}_${stepCounter}`;
  }

  // ========================================
  // NORMALIZE GOAL & CONTEXT
  // ========================================

  const effectiveRegion = goal.targetRegion ?? context.defaultRegion ?? "UK";
  const effectiveCountry = context.defaultCountry ?? "GB";
  const persona = goal.targetPersona ?? "target customers";
  const volume = goal.volume ?? 50;
  const timing = goal.timing ?? "asap";

  // ========================================
  // STEP 1: GOOGLE_PLACES_SEARCH
  // ========================================

  const googlePlacesStepId = nextStepId("google_places");

  steps.push({
    id: googlePlacesStepId,
    label: "Find candidate businesses via Google Places",
    tool: "GOOGLE_PLACES_SEARCH",
    params: {
      query: persona,
      region: effectiveRegion,
      country: effectiveCountry,
      maxResults: volume * 2 // Over-fetch so we can filter later
    },
    dependsOn: [],
    note: "Initial business discovery from Google Places based on persona and region."
  });

  // ========================================
  // STEP 2: HUNTER_DOMAIN_LOOKUP
  // ========================================

  const hunterDomainStepId = nextStepId("hunter_domain_lookup");

  steps.push({
    id: hunterDomainStepId,
    label: "Look up domains for candidate businesses",
    tool: "HUNTER_DOMAIN_LOOKUP",
    params: {
      sourceStepId: googlePlacesStepId,
      country: effectiveCountry
    },
    dependsOn: [googlePlacesStepId],
    note: "Take business names from Google Places and find domains."
  });

  // ========================================
  // STEP 3: HUNTER_ENRICH
  // ========================================

  const hunterEnrichStepId = nextStepId("hunter_enrich");

  steps.push({
    id: hunterEnrichStepId,
    label: "Find target contacts at those domains",
    tool: "HUNTER_ENRICH",
    params: {
      sourceStepId: hunterDomainStepId,
      roleHint: persona,
      maxContactsPerDomain: 2
    },
    dependsOn: [hunterDomainStepId],
    note: "Use Hunter to find contacts that match the target persona."
  });

  // ========================================
  // STEP 4: LEAD_LIST_SAVE
  // ========================================

  const saveListStepId = nextStepId("lead_list_save");

  steps.push({
    id: saveListStepId,
    label: "Save enriched leads to a list",
    tool: "LEAD_LIST_SAVE",
    params: {
      sourceStepId: hunterEnrichStepId,
      listName: goal.rawGoal || "Lead list",
      region: effectiveRegion,
      persona,
      estimatedVolume: volume
    },
    dependsOn: [hunterEnrichStepId],
    note: "Store all enriched leads under a named list in Wyshbone."
  });

  // ========================================
  // STEP 5: EMAIL_SEQUENCE_SETUP (conditional)
  // ========================================

  const wantsEmail =
    !goal.preferredChannels || goal.preferredChannels.includes("email");

  if (wantsEmail && context.defaultFromIdentityId) {
    const emailSeqStepId = nextStepId("email_sequence");

    steps.push({
      id: emailSeqStepId,
      label: "Set up outbound email sequence",
      tool: "EMAIL_SEQUENCE_SETUP",
      params: {
        sourceListStepId: saveListStepId,
        campaignName: goal.rawGoal || "Outbound campaign",
        fromIdentityId: context.defaultFromIdentityId,
        estimatedVolume: volume,
        startTiming: timing
      },
      dependsOn: [saveListStepId],
      note: "Create an email sequence in the outreach system targeting the saved leads."
    });
  }

  // ========================================
  // STEP 6: MONITOR_SETUP (conditional)
  // ========================================

  if (goal.includeMonitoring) {
    const monitorStepId = nextStepId("monitor");

    steps.push({
      id: monitorStepId,
      label: "Set up ongoing monitoring for this lead list",
      tool: "MONITOR_SETUP",
      params: {
        sourceListStepId: saveListStepId,
        cadence: "weekly",
        signalTypes: ["new_reviews", "profile_changes"]
      },
      dependsOn: [saveListStepId],
      note: "Configure background monitoring to surface future signals for this list."
    });
  }

  // ========================================
  // CONSTRUCT FINAL PLAN
  // ========================================

  const planId = `lead_plan_${Date.now()}`;

  const plan: LeadGenPlan = {
    id: planId,
    title: goal.rawGoal || "Lead generation plan",
    rawGoal: goal.rawGoal,
    goal,
    context,
    steps,
    createdAt: new Date().toISOString(),
    priority: "normal"
  };

  return plan;
}

// ========================================
// EXAMPLE USAGE (for testing)
// ========================================

/**
 * Example usage showing how to create a lead generation plan.
 * This demonstrates the expected output for a typical goal.
 */
export function exampleLeadGenPlan(): LeadGenPlan {
  return planLeadGeneration(
    {
      rawGoal: "Find 50 pubs in the North West and email the landlords this week",
      targetRegion: "North West",
      targetPersona: "pub landlords",
      volume: 50,
      timing: "this_week",
      preferredChannels: ["email"],
      includeMonitoring: true
    },
    {
      userId: "test-user-123",
      accountId: "test-account",
      defaultRegion: "UK",
      defaultCountry: "GB",
      defaultFromIdentityId: "from-identity-1"
    }
  );
}
