export enum FailureClassification {
  INTERPRETATION_FAILURE = 'INTERPRETATION_FAILURE',
  PLANNER_FAILURE = 'PLANNER_FAILURE',
  DISCOVERY_FAILURE = 'DISCOVERY_FAILURE',
  CRAWL_FAILURE = 'CRAWL_FAILURE',
  EVIDENCE_EXTRACTION_FAILURE = 'EVIDENCE_EXTRACTION_FAILURE',
  TOWER_JUDGEMENT_FAILURE = 'TOWER_JUDGEMENT_FAILURE',
  REPLAN_FAILURE = 'REPLAN_FAILURE',
  UI_TRUTH_FAILURE = 'UI_TRUTH_FAILURE',
  NONE = 'NONE',
}
